### ISSUE TITLE
How to run eklt in real time

### ISSUE THREAD

**Issue by StancyMiller** [uzh-rpg/rpg_eklt#5]
Thank you for releasing the code, which taught me a lot.
  I've followed the guide and run
`roslaunch eklt eklt.launch tracks_file_txt:=/tmp/eklt_example/tracks.txt v:=1`
`rosbag play /tmp/eklt_example/boxes_6dof.bag`.
  But I found that the running speed seemed very low: when the rosbag playing ended, the tracking and displaying algorithm was still running for a very long time, which seems not consistent with your video on Youtube.
  Could you tell me how to speed up the running process, and how to run eklt in real time? Is it possible to change some configurations, or simply stop displaying?
  Thank you.

**Comment by danielgehrig18** [comment]
Hi StancyMiller,

The code does not run real-time, however, the tracks can be visualized in
post processing. Turning off the visualization indeed speeds up code by ~2x
so that may be a good option.
If you want to run it faster it might make sense to look into reducing the
number of optimization cycles or increasing the number of new events before
a new update.

**Comment by StancyMiller** [comment]
@danielgehrig18 
Thank you😀

**Comment by Doch88** [comment]
@StancyMiller in the past year we tried to speed up the algorithm using a multithreading approach. It does not run real-time, but you can obtain an improvement of about ~6.5x on a Ryzen 5. Here's our work: [https://github.com/Doch88/rpg_eklt_multithreading](https://github.com/Doch88/rpg_eklt_multithreading)
